version: '2'
services:
    storiyo-app:
        image: storiyo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://storiyo-postgresql:5432/STORIYO
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=storiyo-elasticsearch:9300
    storiyo-postgresql:
        extends:
            file: postgresql.yml
            service: storiyo-postgresql
    storiyo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: storiyo-elasticsearch
